export const ADD_NAME = 'ADD_NAME'
export const ADD_LOCATION = 'ADD_LOCATION'
export const ADD_EMAIL = 'ADD_EMAIL'
export const ADD_COMPANY = 'ADD_COMPANY'
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES'
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'
